import Head from 'next/head'
import { Inter } from '@next/font/google'
import { FaRegComments } from 'react-icons/fa'
import { Disclosure } from "@headlessui/react";
import { GiHamburgerMenu } from "react-icons/gi";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>

      <Disclosure as="nav">
        <Disclosure.Button className="absolute top-4 right-4 inline-flex items-center peer justify-center rounded-md p-2 text-gray-800 hover:bg-gray-900 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white group">
          <GiHamburgerMenu
            className="block md:hidden h-6 w-6"
            aria-hidden="true"
          />
        </Disclosure.Button>


        <div className="text-3xl">asa</div>

        </Disclosure>


        <FaRegComments />
        hola
      </div>
    </>
  )
}
